// import { StoreType } from "../(userend)/types/store";

const AllStores = [{
    "_id": {
      "$oid": "66c70e627d81d1e34aee75d1"
    },
    "id": "3984d786-1e86-4d4a-8334-3b222891daff",
    "storeImportId": 0,
    "store_website": "https://007store.com",
    "store_priority": null,
    "store_affiliate_url": null,
    "name": "007Store",
    "slug": null,
    "status": "PAUSED",
    "lastUpdate": null,
    "creationDate": "2024-07-26T07:02:12.000Z",
    "storeImportLastUpdate": null,
    "botTestingNote": null,
    "botTestingStatus": null,
    "store_logo": "https://www.rankcdn.com/cdn-cgi/image/quality=90,onerror=redirect,format=webp,fit=cover,width=150,height=150/couponseeker.com/007Store.jpg",
    "store_category": "7f04e84c-6f33-4c72-a244-3ee3f7c24931",
    "store_search_target": "",
    "store_tag": null,
    "store_facebook": "",
    "store_instagram": "",
    "store_twitter": "",
    "store_youtube": "",
    "store_email": "",
    "store_phone": null,
    "store_help_desk": "",
    "store_contact_page": "",
    "store_country": "",
    "store_how_to_use_coupon": "",
    "store_FAQ": null,
    "store_program_platform": null,
    "store_disclaimer": "",
    "store_template": "",
    "store_rating": 4,
    "store_view_count": null,
    "store_average_rating": null,
    "store_location_code": null,
    "bestDiscount": null,
    "store_description": "",
    "store_name": "007Store",
    "store_slug": null,
    "store_status": "PAUSED",
    "store_affiliate_link": "",
    "store_priority_score": null,
    "store_best_discount": null,
    "store_tags": "",
    "store_tiktok": "",
    "store_phone_number": "",
    "store_address": "",
    "store_last_updated": {
      "$date": "2024-08-22T10:09:37.715Z"
    },
    "store_last_checked": {
      "$date": "2024-08-22T10:09:37.715Z"
    },
    "store_saving_tips": "",
    "store_faq": "",
    "store_payment_modes": ""
  },
  {
    "_id": {
      "$oid": "66c70e627d81d1e34aee75d2"
    },
    "id": "308",
    "storeImportId": 1,
    "store_website": "123ink.ca",
    "store_priority": "low",
    "store_affiliate_url": "https://alrigh.com/out/041850",
    "name": "123ink.ca",
    "slug": "123ink.ca",
    "status": "PAUSED",
    "lastUpdate": "2023-08-02T10:28:19.000Z",
    "creationDate": "2023-08-02T10:15:05.000Z",
    "storeImportLastUpdate": "2023-08-02T10:26:21.000Z",
    "botTestingNote": null,
    "botTestingStatus": null,
    "store_logo": "",
    "store_category": null,
    "store_search_target": "",
    "store_tag": null,
    "store_facebook": "",
    "store_instagram": "",
    "store_twitter": "",
    "store_youtube": "",
    "store_email": "",
    "store_phone": null,
    "store_help_desk": "",
    "store_contact_page": "",
    "store_country": "",
    "store_how_to_use_coupon": "",
    "store_FAQ": null,
    "store_program_platform": null,
    "store_disclaimer": "",
    "store_template": "",
    "store_rating": null,
    "store_view_count": null,
    "store_average_rating": null,
    "store_location_code": null,
    "bestDiscount": null,
    "store_description": "",
    "store_name": "123ink.ca",
    "store_slug": "123ink.ca",
    "store_status": "PAUSED",
    "store_affiliate_link": "",
    "store_priority_score": null,
    "store_best_discount": null,
    "store_tags": "",
    "store_tiktok": "",
    "store_phone_number": "",
    "store_address": "",
    "store_last_updated": {
      "$date": "2024-08-22T10:09:37.715Z"
    },
    "store_last_checked": {
      "$date": "2024-08-22T10:09:37.715Z"
    },
    "store_saving_tips": "",
    "store_faq": "",
    "store_payment_modes": ""
  },
  {
    "_id": {
      "$oid": "66c70e627d81d1e34aee75d3"
    },
    "id": "364",
    "storeImportId": 1,
    "store_website": "1mg.com",
    "store_priority": "low",
    "store_affiliate_url": "https://alrigh.com/out/tat6bl",
    "name": "1mg",
    "slug": "1mg",
    "status": "PAUSED",
    "lastUpdate": null,
    "creationDate": "2023-08-02T10:15:05.000Z",
    "storeImportLastUpdate": "2023-08-02T10:26:21.000Z",
    "botTestingNote": null,
    "botTestingStatus": null,
    "store_logo": "",
    "store_category": null,
    "store_search_target": "",
    "store_tag": null,
    "store_facebook": "",
    "store_instagram": "",
    "store_twitter": "",
    "store_youtube": "",
    "store_email": "",
    "store_phone": null,
    "store_help_desk": "",
    "store_contact_page": "",
    "store_country": "",
    "store_how_to_use_coupon": "",
    "store_FAQ": null,
    "store_program_platform": null,
    "store_disclaimer": "",
    "store_template": "",
    "store_rating": null,
    "store_view_count": null,
    "store_average_rating": null,
    "store_location_code": null,
    "bestDiscount": null,
    "store_description": "",
    "store_name": "1mg",
    "store_slug": "1mg",
    "store_status": "PAUSED",
    "store_affiliate_link": "",
    "store_priority_score": null,
    "store_best_discount": null,
    "store_tags": "",
    "store_tiktok": "",
    "store_phone_number": "",
    "store_address": "",
    "store_last_updated": {
      "$date": "2024-08-22T10:09:37.715Z"
    },
    "store_last_checked": {
      "$date": "2024-08-22T10:09:37.715Z"
    },
    "store_saving_tips": "",
    "store_faq": "",
    "store_payment_modes": ""
  },
  {
    "_id": {
      "$oid": "66c70e627d81d1e34aee75d4"
    },
    "id": "18dc0c82-159a-441a-a775-f75bd596de1a",
    "storeImportId": 0,
    "store_website": "https://www.24houranswers.com",
    "store_priority": null,
    "store_affiliate_url": null,
    "name": "24HourAnswers.com",
    "slug": null,
    "status": "PAUSED",
    "lastUpdate": null,
    "creationDate": "2024-07-26T07:02:13.000Z",
    "storeImportLastUpdate": null,
    "botTestingNote": null,
    "botTestingStatus": null,
    "store_logo": "https://www.rankcdn.com/cdn-cgi/image/quality=90,onerror=redirect,format=webp,fit=cover,width=150,height=150/couponseeker.com/24houranswers.com-coupon-codes.jpg",
    "store_category": "c2309773-bf45-43b6-8f3c-20867a987a4c",
    "store_search_target": "",
    "store_tag": null,
    "store_facebook": "",
    "store_instagram": "",
    "store_twitter": "",
    "store_youtube": "",
    "store_email": "",
    "store_phone": null,
    "store_help_desk": "",
    "store_contact_page": "",
    "store_country": "",
    "store_how_to_use_coupon": "",
    "store_FAQ": null,
    "store_program_platform": null,
    "store_disclaimer": "",
    "store_template": "",
    "store_rating": null,
    "store_view_count": null,
    "store_average_rating": null,
    "store_location_code": null,
    "bestDiscount": null,
    "store_description": "",
    "store_name": "24HourAnswers.com",
    "store_slug": null,
    "store_status": "PAUSED",
    "store_affiliate_link": "",
    "store_priority_score": null,
    "store_best_discount": null,
    "store_tags": "",
    "store_tiktok": "",
    "store_phone_number": "",
    "store_address": "",
    "store_last_updated": {
      "$date": "2024-08-22T10:09:37.715Z"
    },
    "store_last_checked": {
      "$date": "2024-08-22T10:09:37.715Z"
    },
    "store_saving_tips": "",
    "store_faq": "",
    "store_payment_modes": ""
  },
  {
    "_id": {
      "$oid": "66c70e627d81d1e34aee75d5"
    },
    "id": "cfea3207-23e1-435b-85ec-c0ec750a4a71",
    "storeImportId": 0,
    "store_website": "https://2sand.com",
    "store_priority": null,
    "store_affiliate_url": null,
    "name": "2Sand",
    "slug": null,
    "status": "PAUSED",
    "lastUpdate": null,
    "creationDate": "2024-07-26T07:02:13.000Z",
    "storeImportLastUpdate": null,
    "botTestingNote": null,
    "botTestingStatus": null,
    "store_logo": "https://www.rankcdn.com/cdn-cgi/image/quality=90,onerror=redirect,format=webp,fit=cover,width=150,height=150/couponseeker.com/2Sand-Coupon-Codes.jpg",
    "store_category": "300f5d93-6917-4030-96a2-399e7ca2e6d7",
    "store_search_target": "",
    "store_tag": null,
    "store_facebook": "",
    "store_instagram": "",
    "store_twitter": "",
    "store_youtube": "",
    "store_email": "",
    "store_phone": null,
    "store_help_desk": "",
    "store_contact_page": "",
    "store_country": "",
    "store_how_to_use_coupon": "",
    "store_FAQ": null,
    "store_program_platform": null,
    "store_disclaimer": "",
    "store_template": "",
    "store_rating": null,
    "store_view_count": null,
    "store_average_rating": null,
    "store_location_code": null,
    "bestDiscount": null,
    "store_description": "",
    "store_name": "2Sand",
    "store_slug": null,
    "store_status": "PAUSED",
    "store_affiliate_link": "",
    "store_priority_score": null,
    "store_best_discount": null,
    "store_tags": "",
    "store_tiktok": "",
    "store_phone_number": "",
    "store_address": "",
    "store_last_updated": {
      "$date": "2024-08-22T10:09:37.715Z"
    },
    "store_last_checked": {
      "$date": "2024-08-22T10:09:37.715Z"
    },
    "store_saving_tips": "",
    "store_faq": "",
    "store_payment_modes": ""
  },
  {
    "_id": {
      "$oid": "66c70e627d81d1e34aee75d6"
    },
    "id": "482",
    "storeImportId": 1,
    "store_website": "4cornerscannabis.com",
    "store_priority": "low",
    "store_affiliate_url": "https://alrigh.com/out/rnp6ud",
    "name": "4 Corners Cannabis",
    "slug": "4-corners-cannabis",
    "status": "ACTIVE",
    "lastUpdate": "2024-08-01T06:47:55.000Z",
    "creationDate": "2023-08-02T10:15:05.000Z",
    "storeImportLastUpdate": "2023-08-02T10:26:21.000Z",
    "botTestingNote": null,
    "botTestingStatus": null,
    "store_logo": "",
    "store_category": null,
    "store_search_target": "",
    "store_tag": null,
    "store_facebook": "",
    "store_instagram": "",
    "store_twitter": "",
    "store_youtube": "",
    "store_email": "",
    "store_phone": null,
    "store_help_desk": "",
    "store_contact_page": "",
    "store_country": "",
    "store_how_to_use_coupon": "",
    "store_FAQ": null,
    "store_program_platform": null,
    "store_disclaimer": "",
    "store_template": "",
    "store_rating": null,
    "store_view_count": null,
    "store_average_rating": null,
    "store_location_code": "US",
    "bestDiscount": null,
    "store_description": "",
    "store_name": "4 Corners Cannabis",
    "store_slug": "4-corners-cannabis",
    "store_status": "ACTIVE",
    "store_affiliate_link": "",
    "store_priority_score": null,
    "store_best_discount": null,
    "store_tags": "",
    "store_tiktok": "",
    "store_phone_number": "",
    "store_address": "",
    "store_last_updated": {
      "$date": "2024-08-22T10:09:37.715Z"
    },
    "store_last_checked": {
      "$date": "2024-08-22T10:09:37.715Z"
    },
    "store_saving_tips": "",
    "store_faq": "",
    "store_payment_modes": ""
  },
  {
    "_id": {
      "$oid": "66c70e627d81d1e34aee75d7"
    },
    "id": "328",
    "storeImportId": 1,
    "store_website": "4knines.com",
    "store_priority": "moderate",
    "store_affiliate_url": "https://alrigh.com/out/a7iycy",
    "name": "4knines",
    "slug": "4knines",
    "status": "ACTIVE",
    "lastUpdate": "2024-07-30T11:38:28.000Z",
    "creationDate": "2023-08-02T10:15:05.000Z",
    "storeImportLastUpdate": "2023-08-02T10:26:21.000Z",
    "botTestingNote": null,
    "botTestingStatus": null,
    "store_logo": "",
    "store_category": null,
    "store_search_target": "",
    "store_tag": null,
    "store_facebook": "",
    "store_instagram": "",
    "store_twitter": "",
    "store_youtube": "",
    "store_email": "",
    "store_phone": null,
    "store_help_desk": "",
    "store_contact_page": "",
    "store_country": "",
    "store_how_to_use_coupon": "",
    "store_FAQ": null,
    "store_program_platform": null,
    "store_disclaimer": "",
    "store_template": "",
    "store_rating": null,
    "store_view_count": null,
    "store_average_rating": null,
    "store_location_code": null,
    "bestDiscount": null,
    "store_description": "",
    "store_name": "4knines",
    "store_slug": "4knines",
    "store_status": "ACTIVE",
    "store_affiliate_link": "",
    "store_priority_score": null,
    "store_best_discount": null,
    "store_tags": "",
    "store_tiktok": "",
    "store_phone_number": "",
    "store_address": "",
    "store_last_updated": {
      "$date": "2024-08-22T10:09:37.715Z"
    },
    "store_last_checked": {
      "$date": "2024-08-22T10:09:37.715Z"
    },
    "store_saving_tips": "",
    "store_faq": "",
    "store_payment_modes": ""
  },
  {
    "_id": {
      "$oid": "66c70e627d81d1e34aee75d8"
    },
    "id": "229",
    "storeImportId": 1,
    "store_website": "5percentnutrition.com",
    "store_priority": "low",
    "store_affiliate_url": "https://alrigh.com/out/7y4577",
    "name": "5 Percent Nutrition",
    "slug": "5-percent-nutrition",
    "status": "PAUSED",
    "lastUpdate": null,
    "creationDate": "2023-08-02T10:15:05.000Z",
    "storeImportLastUpdate": "2023-08-02T10:26:21.000Z",
    "botTestingNote": null,
    "botTestingStatus": null,
    "store_logo": "",
    "store_category": null,
    "store_search_target": "",
    "store_tag": null,
    "store_facebook": "",
    "store_instagram": "",
    "store_twitter": "",
    "store_youtube": "",
    "store_email": "",
    "store_phone": null,
    "store_help_desk": "",
    "store_contact_page": "",
    "store_country": "",
    "store_how_to_use_coupon": "",
    "store_FAQ": null,
    "store_program_platform": null,
    "store_disclaimer": "",
    "store_template": "",
    "store_rating": null,
    "store_view_count": null,
    "store_average_rating": null,
    "store_location_code": null,
    "bestDiscount": null,
    "store_description": "",
    "store_name": "5 Percent Nutrition",
    "store_slug": "5-percent-nutrition",
    "store_status": "PAUSED",
    "store_affiliate_link": "",
    "store_priority_score": null,
    "store_best_discount": null,
    "store_tags": "",
    "store_tiktok": "",
    "store_phone_number": "",
    "store_address": "",
    "store_last_updated": {
      "$date": "2024-08-22T10:09:37.715Z"
    },
    "store_last_checked": {
      "$date": "2024-08-22T10:09:37.715Z"
    },
    "store_saving_tips": "",
    "store_faq": "",
    "store_payment_modes": ""
  },
  {
    "_id": {
      "$oid": "66c70e627d81d1e34aee75d9"
    },
    "id": "95a978dc-853a-4c37-a481-d6830429c8c9",
    "storeImportId": 0,
    "store_website": "https://abeka.com",
    "store_priority": null,
    "store_affiliate_url": null,
    "name": "A Beka Book",
    "slug": null,
    "status": "PAUSED",
    "lastUpdate": "2024-07-26T11:22:13.000Z",
    "creationDate": "2024-07-26T11:18:10.000Z",
    "storeImportLastUpdate": null,
    "botTestingNote": null,
    "botTestingStatus": null,
    "store_logo": "",
    "store_category": "afbe1be7-a0ba-48ab-93d4-945e58351a7d",
    "store_search_target": "",
    "store_tag": null,
    "store_facebook": "//www.facebook.com/AbekaChristianSchool",
    "store_instagram": "//www.instagram.com/abekahomeschool/",
    "store_twitter": "",
    "store_youtube": "",
    "store_email": "",
    "store_phone": null,
    "store_help_desk": "",
    "store_contact_page": "",
    "store_country": "",
    "store_how_to_use_coupon": "",
    "store_FAQ": null,
    "store_program_platform": null,
    "store_disclaimer": "",
    "store_template": "",
    "store_rating": null,
    "store_view_count": null,
    "store_average_rating": null,
    "store_location_code": null,
    "bestDiscount": null,
    "store_description": "Abeka.com is an online store that specializes in educational resources primarily for homeschooling parents and Christian schools. They offer a wide range of materials for various grades, from kindergarten through high school. These products include textbooks, workbooks, teaching guides, and even video lessons. Their curriculum covers subjects like math, science, languages, social studies and more—all from a Christian perspective. Abeka is known for its comprehensive and rigorous curricula designed to provide solid academic foundations while embedding Christian values. Whether you are a veteran educator or a new homeschooling parent, Abeka.com offers resources to help guide you through your educational journey.",
    "store_name": "A Beka Book",
    "store_slug": null,
    "store_status": "PAUSED",
    "store_affiliate_link": "",
    "store_priority_score": null,
    "store_best_discount": null,
    "store_tags": "",
    "store_tiktok": "",
    "store_phone_number": "",
    "store_address": "",
    "store_last_updated": {
      "$date": "2024-08-22T10:09:37.715Z"
    },
    "store_last_checked": {
      "$date": "2024-08-22T10:09:37.715Z"
    },
    "store_saving_tips": "",
    "store_faq": "",
    "store_payment_modes": ""
  },
  {
    "_id": {
      "$oid": "66c70e627d81d1e34aee75da"
    },
    "id": "0f761354-5fb3-4cab-afc0-79ceb1053d86",
    "storeImportId": 0,
    "store_website": "https://abookapart.com",
    "store_priority": null,
    "store_affiliate_url": null,
    "name": "A Book Apart",
    "slug": null,
    "status": "PAUSED",
    "lastUpdate": null,
    "creationDate": "2024-07-26T11:18:10.000Z",
    "storeImportLastUpdate": null,
    "botTestingNote": null,
    "botTestingStatus": null,
    "store_logo": "",
    "store_category": "afbe1be7-a0ba-48ab-93d4-945e58351a7d",
    "store_search_target": "",
    "store_tag": null,
    "store_facebook": "",
    "store_instagram": "http://instagram.com/abookapart",
    "store_twitter": "http://twitter.com/abookapart",
    "store_youtube": "",
    "store_email": "",
    "store_phone": null,
    "store_help_desk": "",
    "store_contact_page": "",
    "store_country": "",
    "store_how_to_use_coupon": "",
    "store_FAQ": null,
    "store_program_platform": null,
    "store_disclaimer": "",
    "store_template": "",
    "store_rating": null,
    "store_view_count": null,
    "store_average_rating": null,
    "store_location_code": null,
    "bestDiscount": null,
    "store_description": "Abookapart.com is an online bookstore primarily targeting web designers and developers. It offers a range of concise and practical books that focus on specific topics in the field of web design and development. The content ranges from HTML, CSS, content strategy to responsive web design, and much more. For professionals looking to expand their knowledge, or beginners eager to learn the basics, this site could be quite handy. Each book on the site is written by a recognized expert in their respective field, ensuring high-quality and relevant content. The books are available in both paper and e-book formats. While it's not a place to buy your next novel, it's a helpful resource for those interested in web design and development.",
    "store_name": "A Book Apart",
    "store_slug": null,
    "store_status": "PAUSED",
    "store_affiliate_link": "",
    "store_priority_score": null,
    "store_best_discount": null,
    "store_tags": "",
    "store_tiktok": "",
    "store_phone_number": "",
    "store_address": "",
    "store_last_updated": {
      "$date": "2024-08-22T10:09:37.715Z"
    },
    "store_last_checked": {
      "$date": "2024-08-22T10:09:37.715Z"
    },
    "store_saving_tips": "",
    "store_faq": "",
    "store_payment_modes": ""
  },
  {
    "_id": {
      "$oid": "66c70e627d81d1e34aee75db"
    },
    "id": "54af20a3-a341-4820-8868-ed884b68b9a9",
    "storeImportId": 0,
    "store_website": "https://abriefaffair.com",
    "store_priority": null,
    "store_affiliate_url": null,
    "name": "A Brief Affair",
    "slug": null,
    "status": "PAUSED",
    "lastUpdate": null,
    "creationDate": "2024-07-26T11:18:10.000Z",
    "storeImportLastUpdate": null,
    "botTestingNote": null,
    "botTestingStatus": null,
    "store_logo": "",
    "store_category": "3cdf31e3-b867-4611-bf36-e464ac92cb2a",
    "store_search_target": "",
    "store_tag": null,
    "store_facebook": "",
    "store_instagram": "",
    "store_twitter": "",
    "store_youtube": "",
    "store_email": "",
    "store_phone": null,
    "store_help_desk": "",
    "store_contact_page": "",
    "store_country": "",
    "store_how_to_use_coupon": "",
    "store_FAQ": null,
    "store_program_platform": null,
    "store_disclaimer": "",
    "store_template": "",
    "store_rating": null,
    "store_view_count": null,
    "store_average_rating": null,
    "store_location_code": null,
    "bestDiscount": null,
    "store_description": "",
    "store_name": "A Brief Affair",
    "store_slug": null,
    "store_status": "PAUSED",
    "store_affiliate_link": "",
    "store_priority_score": null,
    "store_best_discount": null,
    "store_tags": "",
    "store_tiktok": "",
    "store_phone_number": "",
    "store_address": "",
    "store_last_updated": {
      "$date": "2024-08-22T10:09:37.715Z"
    },
    "store_last_checked": {
      "$date": "2024-08-22T10:09:37.715Z"
    },
    "store_saving_tips": "",
    "store_faq": "",
    "store_payment_modes": ""
  },
  {
    "_id": {
      "$oid": "66c70e627d81d1e34aee75dc"
    },
    "id": "975f74f3-40ac-4abc-8b62-0a0e17e12d61",
    "storeImportId": 0,
    "store_website": "https://bellaromacandle.com",
    "store_priority": null,
    "store_affiliate_url": null,
    "name": "A Candle Company",
    "slug": null,
    "status": "PAUSED",
    "lastUpdate": null,
    "creationDate": "2024-07-26T11:18:10.000Z",
    "storeImportLastUpdate": null,
    "botTestingNote": null,
    "botTestingStatus": null,
    "store_logo": "",
    "store_category": "ef497a66-8f60-49da-a262-020f0b33ec33",
    "store_search_target": "",
    "store_tag": null,
    "store_facebook": "",
    "store_instagram": "",
    "store_twitter": "",
    "store_youtube": "",
    "store_email": "",
    "store_phone": null,
    "store_help_desk": "",
    "store_contact_page": "",
    "store_country": "",
    "store_how_to_use_coupon": "",
    "store_FAQ": null,
    "store_program_platform": null,
    "store_disclaimer": "",
    "store_template": "",
    "store_rating": null,
    "store_view_count": null,
    "store_average_rating": null,
    "store_location_code": null,
    "bestDiscount": null,
    "store_description": "\"Bellaroma Candle\" is a web-based outlet that specializes in selling a wide array of scented candles. These candles are intended to enhance the ambiance of your personal space with their appealing aromas. From seasonal to everyday scents, the store has a diverse range of unique candles for you to choose from. Lavender, vanilla, and spice are just a few examples of the numerous fragrances offered. Each candle is crafted carefully to ensure quality and a long-lasting scent. The site is user-friendly, allowing for easy browsing and shopping. You can conveniently shop for your favorite candle type based on scent, size, or occasion right from the comfort of your home.",
    "store_name": "A Candle Company",
    "store_slug": null,
    "store_status": "PAUSED",
    "store_affiliate_link": "",
    "store_priority_score": null,
    "store_best_discount": null,
    "store_tags": "",
    "store_tiktok": "",
    "store_phone_number": "",
    "store_address": "",
    "store_last_updated": {
      "$date": "2024-08-22T10:09:37.715Z"
    },
    "store_last_checked": {
      "$date": "2024-08-22T10:09:37.715Z"
    },
    "store_saving_tips": "",
    "store_faq": "",
    "store_payment_modes": ""
  },
  {
    "_id": {
      "$oid": "66c70e627d81d1e34aee75dd"
    },
    "id": "64ef2fd9-b8f0-4531-ba94-a3b679b03fa5",
    "storeImportId": 0,
    "store_website": "https://acherryontop.com",
    "store_priority": null,
    "store_affiliate_url": null,
    "name": "A Cherry on Top",
    "slug": null,
    "status": "PAUSED",
    "lastUpdate": null,
    "creationDate": "2024-07-26T11:18:10.000Z",
    "storeImportLastUpdate": null,
    "botTestingNote": null,
    "botTestingStatus": null,
    "store_logo": "",
    "store_category": "941ef28b-7a91-4261-b407-c83630eae33a",
    "store_search_target": "",
    "store_tag": null,
    "store_facebook": "https://www.facebook.com/acherryontopcrafts",
    "store_instagram": "https://www.instagram.com/acherryontop_crafts",
    "store_twitter": "https://twitter.com/acherryontop",
    "store_youtube": "",
    "store_email": "",
    "store_phone": null,
    "store_help_desk": "",
    "store_contact_page": "",
    "store_country": "",
    "store_how_to_use_coupon": "",
    "store_FAQ": null,
    "store_program_platform": null,
    "store_disclaimer": "",
    "store_template": "",
    "store_rating": null,
    "store_view_count": null,
    "store_average_rating": null,
    "store_location_code": null,
    "bestDiscount": null,
    "store_description": "\"ACherryOnTop.com\" is an online store dedicated to arts and crafts enthusiasts. It's a one-stop shop for a wide variety of crafting supplies, from scrapbooking items, stickers, and stamps to a range of paints, glitter, and crafting tools. Whether you're into card making, mixed media, journaling, or DIY home decor, you'll find the necessary supplies here. The store also offers project ideas and hosts an active community section where crafters can exchange ideas and advice. Besides individual products, they sell bundles and kits that are especially useful for beginners or those undertaking a specific project. Simple ordering process, prompt shipping and good customer service are some of the notable features of this store.",
    "store_name": "A Cherry on Top",
    "store_slug": null,
    "store_status": "PAUSED",
    "store_affiliate_link": "",
    "store_priority_score": null,
    "store_best_discount": null,
    "store_tags": "",
    "store_tiktok": "",
    "store_phone_number": "",
    "store_address": "",
    "store_last_updated": {
      "$date": "2024-08-22T10:09:37.715Z"
    },
    "store_last_checked": {
      "$date": "2024-08-22T10:09:37.715Z"
    },
    "store_saving_tips": "",
    "store_faq": "",
    "store_payment_modes": ""
  },
  {
    "_id": {
      "$oid": "66c70e627d81d1e34aee75de"
    },
    "id": "75d0eef0-bcdf-4e56-a9a3-aac9c4ef31ea",
    "storeImportId": 0,
    "store_website": "https://achildsdream.com",
    "store_priority": null,
    "store_affiliate_url": null,
    "name": "A Child's Dream",
    "slug": null,
    "status": "PAUSED",
    "lastUpdate": null,
    "creationDate": "2024-07-26T11:49:42.000Z",
    "storeImportLastUpdate": null,
    "botTestingNote": null,
    "botTestingStatus": null,
    "store_logo": "",
    "store_category": "093b237b-7f3c-49cf-93c5-a3dc250d8a2e",
    "store_search_target": "",
    "store_tag": null,
    "store_facebook": "https://www.facebook.com/achildsdream",
    "store_instagram": "https://www.instagram.com/achildsdreamcrafts/",
    "store_twitter": "",
    "store_youtube": "",
    "store_email": "",
    "store_phone": null,
    "store_help_desk": "",
    "store_contact_page": "",
    "store_country": "",
    "store_how_to_use_coupon": "",
    "store_FAQ": null,
    "store_program_platform": null,
    "store_disclaimer": "",
    "store_template": "",
    "store_rating": null,
    "store_view_count": null,
    "store_average_rating": null,
    "store_location_code": null,
    "bestDiscount": null,
    "store_description": "Achildsdream.com is an online store that specializes in selling craft supplies and natural products. It caters to both children and adults and offers a variety of materials, including wool, felt, silk, and wood. The store is also known for its DIY craft kits that kids can engage with to create their own toys or art-pieces. Additionally, achildsdream.com carries educational toys and books with a focus on creativity and learning. This is a great place for parents, educators, or craft enthusiasts looking for high-quality, eco-friendly products to spark creativity and imagination.",
    "store_name": "A Child's Dream",
    "store_slug": null,
    "store_status": "PAUSED",
    "store_affiliate_link": "",
    "store_priority_score": null,
    "store_best_discount": null,
    "store_tags": "",
    "store_tiktok": "",
    "store_phone_number": "",
    "store_address": "",
    "store_last_updated": {
      "$date": "2024-08-22T10:09:37.715Z"
    },
    "store_last_checked": {
      "$date": "2024-08-22T10:09:37.715Z"
    },
    "store_saving_tips": "",
    "store_faq": "",
    "store_payment_modes": ""
  },
  {
    "_id": {
      "$oid": "66c70e627d81d1e34aee75df"
    },
    "id": "94f31bf1-df00-4c02-9134-0358146840a2",
    "storeImportId": 0,
    "store_website": "https://agiftfromnaturecbd.com",
    "store_priority": null,
    "store_affiliate_url": null,
    "name": "A Gift from Nature CBD",
    "slug": null,
    "status": "PAUSED",
    "lastUpdate": null,
    "creationDate": "2024-07-26T13:04:39.000Z",
    "storeImportLastUpdate": null,
    "botTestingNote": null,
    "botTestingStatus": null,
    "store_logo": "",
    "store_category": null,
    "store_search_target": "",
    "store_tag": null,
    "store_facebook": "https://www.facebook.com/agiftfromnaturecbd/",
    "store_instagram": "https://www.instagram.com/agiftfromnatureco/",
    "store_twitter": "",
    "store_youtube": "",
    "store_email": "",
    "store_phone": null,
    "store_help_desk": "",
    "store_contact_page": "",
    "store_country": "",
    "store_how_to_use_coupon": "",
    "store_FAQ": null,
    "store_program_platform": null,
    "store_disclaimer": "",
    "store_template": "",
    "store_rating": null,
    "store_view_count": null,
    "store_average_rating": null,
    "store_location_code": null,
    "bestDiscount": null,
    "store_description": "Agiftfromnaturecbd.com is an online store that sells CBD products. These include CBD oil, edibles, topicals, vape pens, and capsules. They cater to both humans and pets by offering a variety of products designed for different uses. Their goal is to provide natural, high-quality hemp products that can be used as a potential remedy for several ailments. They also aim to educate their customers about the benefits of CBD, offering detailed information about the products they offer. Agiftfromnaturecbd.com is especially popular among people looking for alternative health therapies. It's worth noting, their products are derived from hemp and shouldn't induce a 'high', as they lack significant THC content.",
    "store_name": "A Gift from Nature CBD",
    "store_slug": null,
    "store_status": "PAUSED",
    "store_affiliate_link": "",
    "store_priority_score": null,
    "store_best_discount": null,
    "store_tags": "",
    "store_tiktok": "",
    "store_phone_number": "",
    "store_address": "",
    "store_last_updated": {
      "$date": "2024-08-22T10:09:37.716Z"
    },
    "store_last_checked": {
      "$date": "2024-08-22T10:09:37.716Z"
    },
    "store_saving_tips": "",
    "store_faq": "",
    "store_payment_modes": ""
  },
  {
    "_id": {
      "$oid": "66c70e627d81d1e34aee75e0"
    },
    "id": "0d4fed51-8b9a-4de5-aaa5-4988a36a6eeb",
    "storeImportId": 0,
    "store_website": "https://agrainofsand.com",
    "store_priority": null,
    "store_affiliate_url": null,
    "name": "A Grain of Sand",
    "slug": null,
    "status": "PAUSED",
    "lastUpdate": null,
    "creationDate": "2024-07-26T11:49:42.000Z",
    "storeImportLastUpdate": null,
    "botTestingNote": null,
    "botTestingStatus": null,
    "store_logo": "",
    "store_category": "3cdf31e3-b867-4611-bf36-e464ac92cb2a",
    "store_search_target": "",
    "store_tag": null,
    "store_facebook": "http://www.facebook.com/agosbeads",
    "store_instagram": "https://www.instagram.com/agrainofsandcrystals/",
    "store_twitter": "http://twitter.com/a_grain_of_sand",
    "store_youtube": "",
    "store_email": "",
    "store_phone": null,
    "store_help_desk": "",
    "store_contact_page": "",
    "store_country": "",
    "store_how_to_use_coupon": "",
    "store_FAQ": null,
    "store_program_platform": null,
    "store_disclaimer": "",
    "store_template": "",
    "store_rating": null,
    "store_view_count": null,
    "store_average_rating": null,
    "store_location_code": null,
    "bestDiscount": null,
    "store_description": "\"Agrainofsand.com\" is an online store dedicated to jewelry making supplies and vintage beads. They stock a broad range of items from various eras, including vintage Swarovski crystals, semi-precious beads, and findings. The store is like a treasure trove for craft lovers offering everything that one might need to create unique, handcrafted jewelry. It's particularly acclaimed for its range of rare vintage beads. The website is straightforward to navigate, making it easy to find specific items or explore different product categories. Whether you're a professional designer or a hobbyist, \"agrainofsand.com\" is a valuable resource for all things beading and jewelry-making.",
    "store_name": "A Grain of Sand",
    "store_slug": null,
    "store_status": "PAUSED",
    "store_affiliate_link": "",
    "store_priority_score": null,
    "store_best_discount": null,
    "store_tags": "",
    "store_tiktok": "",
    "store_phone_number": "",
    "store_address": "",
    "store_last_updated": {
      "$date": "2024-08-22T10:09:37.716Z"
    },
    "store_last_checked": {
      "$date": "2024-08-22T10:09:37.716Z"
    },
    "store_saving_tips": "",
    "store_faq": "",
    "store_payment_modes": ""
  },
  {
    "_id": {
      "$oid": "66c70e627d81d1e34aee75e1"
    },
    "id": "8e632e21-3a61-4b9f-ae99-95c062603d0d",
    "storeImportId": 0,
    "store_website": "https://www.alittlebitofpaint.com",
    "store_priority": null,
    "store_affiliate_url": null,
    "name": "A Little Bit of Paint",
    "slug": null,
    "status": "PAUSED",
    "lastUpdate": null,
    "creationDate": "2024-07-26T07:02:09.000Z",
    "storeImportLastUpdate": null,
    "botTestingNote": null,
    "botTestingStatus": null,
    "store_logo": "https://www.rankcdn.com/cdn-cgi/image/quality=90,onerror=redirect,format=webp,fit=cover,width=150,height=150/couponseeker.com/a-little-bit-of-paint-coupon-codes.jpg",
    "store_category": "e0327f8e-abc7-48d2-9ac7-8ddbbcbc7c25",
    "store_search_target": "",
    "store_tag": null,
    "store_facebook": "",
    "store_instagram": "",
    "store_twitter": "",
    "store_youtube": "",
    "store_email": "",
    "store_phone": null,
    "store_help_desk": "",
    "store_contact_page": "",
    "store_country": "",
    "store_how_to_use_coupon": "",
    "store_FAQ": null,
    "store_program_platform": null,
    "store_disclaimer": "",
    "store_template": "",
    "store_rating": null,
    "store_view_count": null,
    "store_average_rating": null,
    "store_location_code": null,
    "bestDiscount": null,
    "store_description": "",
    "store_name": "A Little Bit of Paint",
    "store_slug": null,
    "store_status": "PAUSED",
    "store_affiliate_link": "",
    "store_priority_score": null,
    "store_best_discount": null,
    "store_tags": "",
    "store_tiktok": "",
    "store_phone_number": "",
    "store_address": "",
    "store_last_updated": {
      "$date": "2024-08-22T10:09:37.716Z"
    },
    "store_last_checked": {
      "$date": "2024-08-22T10:09:37.716Z"
    },
    "store_saving_tips": "",
    "store_faq": "",
    "store_payment_modes": ""
  },
  {
    "_id": {
      "$oid": "66c70e627d81d1e34aee75e2"
    },
    "id": "c00cc8f2-a08e-4fd6-8a90-fa4286815f32",
    "storeImportId": 0,
    "store_website": "https://amainhobbies.com",
    "store_priority": null,
    "store_affiliate_url": null,
    "name": "A Main Hobbies",
    "slug": null,
    "status": "PAUSED",
    "lastUpdate": null,
    "creationDate": "2024-07-26T11:49:42.000Z",
    "storeImportLastUpdate": null,
    "botTestingNote": null,
    "botTestingStatus": null,
    "store_logo": "",
    "store_category": "74adc2d7-68dd-4f76-a7b2-4f35d6a7b754",
    "store_search_target": "",
    "store_tag": null,
    "store_facebook": "https://www.facebook.com/amainhobbies",
    "store_instagram": "https://www.instagram.com/amainhobbies/",
    "store_twitter": "",
    "store_youtube": "",
    "store_email": "",
    "store_phone": null,
    "store_help_desk": "",
    "store_contact_page": "",
    "store_country": "",
    "store_how_to_use_coupon": "",
    "store_FAQ": null,
    "store_program_platform": null,
    "store_disclaimer": "",
    "store_template": "",
    "store_rating": null,
    "store_view_count": null,
    "store_average_rating": null,
    "store_location_code": null,
    "bestDiscount": null,
    "store_description": "AmainHobbies.com is a popular online store that specializes in hobby products. Their vast collection includes items for a wide range of hobbies, such as radio-controlled cars, planes, helicopters, and drones. Besides these, they also offer parts and accessories for these models, allowing hobbyists to customize their gear to their preference. Moreover, AmainHobbies.com also provides options for other hobbies such as model trains, slot cars, and rockets. The users appreciate their user-friendly website, which makes it easy to find specific items. They are known for their broad product range, competitive prices, and good customer service, including fast shipping.",
    "store_name": "A Main Hobbies",
    "store_slug": null,
    "store_status": "PAUSED",
    "store_affiliate_link": "",
    "store_priority_score": null,
    "store_best_discount": null,
    "store_tags": "",
    "store_tiktok": "",
    "store_phone_number": "",
    "store_address": "",
    "store_last_updated": {
      "$date": "2024-08-22T10:09:37.716Z"
    },
    "store_last_checked": {
      "$date": "2024-08-22T10:09:37.716Z"
    },
    "store_saving_tips": "",
    "store_faq": "",
    "store_payment_modes": ""
  },
  {
    "_id": {
      "$oid": "66c70e627d81d1e34aee75e3"
    },
    "id": "9cfe8b7d-7e06-421e-bf71-45754df3d3a6",
    "storeImportId": 0,
    "store_website": "https://amatteroffax.com",
    "store_priority": null,
    "store_affiliate_url": null,
    "name": "A Matter of Fax",
    "slug": null,
    "status": "PAUSED",
    "lastUpdate": null,
    "creationDate": "2024-07-26T11:49:42.000Z",
    "storeImportLastUpdate": null,
    "botTestingNote": null,
    "botTestingStatus": null,
    "store_logo": "",
    "store_category": "123e4567-e89b-12d3-a456-426614174000",
    "store_search_target": "",
    "store_tag": null,
    "store_facebook": "",
    "store_instagram": "",
    "store_twitter": "",
    "store_youtube": "",
    "store_email": "",
    "store_phone": null,
    "store_help_desk": "",
    "store_contact_page": "",
    "store_country": "",
    "store_how_to_use_coupon": "",
    "store_FAQ": null,
    "store_program_platform": null,
    "store_disclaimer": "",
    "store_template": "",
    "store_rating": null,
    "store_view_count": null,
    "store_average_rating": null,
    "store_location_code": null,
    "bestDiscount": null,
    "store_description": "\"Amatteroffax.com\" is an online store specializing in digital and electronic devices. The store offers a diverse range of items, such as printers, scanners, fax machines, copiers, shredders, and supplies related to these items. Apart from this, they also sell various types of software and hardware products for both personal and business use. Their offerings are latest in tech and they have products from various well-known brands. However, as the name suggests, they seem to emphasize fax machines and related items. The website is quite user-friendly, with products neatly categorized to make shopping easy for customers. They provide detailed descriptions and specifications for each product, aiding customers in making informed decisions.",
    "store_name": "A Matter of Fax",
    "store_slug": null,
    "store_status": "PAUSED",
    "store_affiliate_link": "",
    "store_priority_score": null,
    "store_best_discount": null,
    "store_tags": "",
    "store_tiktok": "",
    "store_phone_number": "",
    "store_address": "",
    "store_last_updated": {
      "$date": "2024-08-22T10:09:37.716Z"
    },
    "store_last_checked": {
      "$date": "2024-08-22T10:09:37.716Z"
    },
    "store_saving_tips": "",
    "store_faq": "",
    "store_payment_modes": ""
  },
  {
    "_id": {
      "$oid": "66c70e627d81d1e34aee75e4"
    },
    "id": "785b5d92-9d88-4621-b767-d9830a8576a6",
    "storeImportId": 0,
    "store_website": "https://apeainthepod.com",
    "store_priority": null,
    "store_affiliate_url": null,
    "name": "A Pea in the Pod",
    "slug": null,
    "status": "PAUSED",
    "lastUpdate": null,
    "creationDate": "2024-07-26T13:17:59.000Z",
    "storeImportLastUpdate": null,
    "botTestingNote": null,
    "botTestingStatus": null,
    "store_logo": "public/images/storesImage/apeainthepod.com.webp",
    "store_category": "3cdf31e3-b867-4611-bf36-e464ac92cb2a",
    "store_search_target": "",
    "store_tag": null,
    "store_facebook": "https://www.facebook.com/apeainthepod",
    "store_instagram": "https://www.instagram.com/apeainthepodmaternity/",
    "store_twitter": "",
    "store_youtube": "",
    "store_email": "",
    "store_phone": null,
    "store_help_desk": "",
    "store_contact_page": "",
    "store_country": "",
    "store_how_to_use_coupon": "",
    "store_FAQ": null,
    "store_program_platform": null,
    "store_disclaimer": "",
    "store_template": "",
    "store_rating": null,
    "store_view_count": null,
    "store_average_rating": null,
    "store_location_code": null,
    "bestDiscount": null,
    "store_description": "A Pea in the Pod is an online retail shop that offers fashionable maternity clothing. They cater to expecting mothers who want to retain their sense of style during pregnancy. While they're known for high-end designer items, they also have more budget-friendly offerings. The store offers a variety of clothing including dresses, tops, jeans, and much more. All the clothes are designed with both comfort and style in mind, to accommodate the changing body during pregnancy. The website also includes a section with nursing clothes for post-pregnancy. The shop has an easy-to-use layout and allows visitors to sort items by category, size, price, and other filters.",
    "store_name": "A Pea in the Pod",
    "store_slug": null,
    "store_status": "PAUSED",
    "store_affiliate_link": "",
    "store_priority_score": null,
    "store_best_discount": null,
    "store_tags": "",
    "store_tiktok": "",
    "store_phone_number": "",
    "store_address": "",
    "store_last_updated": {
      "$date": "2024-08-22T10:09:37.716Z"
    },
    "store_last_checked": {
      "$date": "2024-08-22T10:09:37.716Z"
    },
    "store_saving_tips": "",
    "store_faq": "",
    "store_payment_modes": ""
  },
  {
    "_id": {
      "$oid": "66c70e627d81d1e34aee75e5"
    },
    "id": "0e9e6440-ad26-4a1a-81d6-c5071f190144",
    "storeImportId": 0,
    "store_website": "https://aplacetofloat.com",
    "store_priority": null,
    "store_affiliate_url": null,
    "name": "A PLACE TO FLOAT",
    "slug": null,
    "status": "PAUSED",
    "lastUpdate": null,
    "creationDate": "2024-07-26T13:17:59.000Z",
    "storeImportLastUpdate": null,
    "botTestingNote": null,
    "botTestingStatus": null,
    "store_logo": "",
    "store_category": "97e4c4ea-a8a4-4aac-b95a-c1dc9c0f1594",
    "store_search_target": "",
    "store_tag": null,
    "store_facebook": "",
    "store_instagram": "",
    "store_twitter": "",
    "store_youtube": "",
    "store_email": "",
    "store_phone": null,
    "store_help_desk": "",
    "store_contact_page": "",
    "store_country": "",
    "store_how_to_use_coupon": "",
    "store_FAQ": null,
    "store_program_platform": null,
    "store_disclaimer": "",
    "store_template": "",
    "store_rating": null,
    "store_view_count": null,
    "store_average_rating": null,
    "store_location_code": null,
    "bestDiscount": null,
    "store_description": "",
    "store_name": "A PLACE TO FLOAT",
    "store_slug": null,
    "store_status": "PAUSED",
    "store_affiliate_link": "",
    "store_priority_score": null,
    "store_best_discount": null,
    "store_tags": "",
    "store_tiktok": "",
    "store_phone_number": "",
    "store_address": "",
    "store_last_updated": {
      "$date": "2024-08-22T10:09:37.716Z"
    },
    "store_last_checked": {
      "$date": "2024-08-22T10:09:37.716Z"
    },
    "store_saving_tips": "",
    "store_faq": "",
    "store_payment_modes": ""
  },
  {
    "_id": {
      "$oid": "66c70e627d81d1e34aee75e6"
    },
    "id": "dfbc82de-6469-4752-9bb1-7b2880991d52",
    "storeImportId": 0,
    "store_website": "https://a-premium.com",
    "store_priority": null,
    "store_affiliate_url": null,
    "name": "A Premium",
    "slug": null,
    "status": "PAUSED",
    "lastUpdate": null,
    "creationDate": "2024-07-26T13:17:59.000Z",
    "storeImportLastUpdate": null,
    "botTestingNote": null,
    "botTestingStatus": null,
    "store_logo": "public/images/storesImage/a-premium.com.webp",
    "store_category": null,
    "store_search_target": "",
    "store_tag": null,
    "store_facebook": "https://www.facebook.com/apremiumauto",
    "store_instagram": "",
    "store_twitter": "",
    "store_youtube": "",
    "store_email": "",
    "store_phone": null,
    "store_help_desk": "",
    "store_contact_page": "",
    "store_country": "",
    "store_how_to_use_coupon": "",
    "store_FAQ": null,
    "store_program_platform": null,
    "store_disclaimer": "",
    "store_template": "",
    "store_rating": null,
    "store_view_count": null,
    "store_average_rating": null,
    "store_location_code": null,
    "bestDiscount": null,
    "store_description": "\"A-premium.com\" is an online store that specializes in selling auto parts. They carry a wide variety of items, ranging from mirrors to brake pads, making it easy for people to find exactly what they need to maintain or repair their vehicles. A key feature of A-premium.com is that they offer parts for a multitude of different car makes and models, so whether you drive a Ford, Toyota or Honda, chances are they've got you covered. In addition to parts, the store also sells car accessories. Shopping on \"A-premium.com\" is a straightforward experience, with organized categories and comprehensive product details. Customers also appreciate the store’s quick shipping, easy return policy, and helpful customer service.",
    "store_name": "A Premium",
    "store_slug": null,
    "store_status": "PAUSED",
    "store_affiliate_link": "",
    "store_priority_score": null,
    "store_best_discount": null,
    "store_tags": "",
    "store_tiktok": "",
    "store_phone_number": "",
    "store_address": "",
    "store_last_updated": {
      "$date": "2024-08-22T10:09:37.716Z"
    },
    "store_last_checked": {
      "$date": "2024-08-22T10:09:37.716Z"
    },
    "store_saving_tips": "",
    "store_faq": "",
    "store_payment_modes": ""
  },
  {
    "_id": {
      "$oid": "66c70e627d81d1e34aee75e7"
    },
    "id": "67f5df19-13d0-4fbd-9a4e-461c4cc6c207",
    "storeImportId": 0,
    "store_website": "https://apupabove.com",
    "store_priority": null,
    "store_affiliate_url": null,
    "name": "A Pup Above",
    "slug": null,
    "status": "PAUSED",
    "lastUpdate": null,
    "creationDate": "2024-07-26T13:17:59.000Z",
    "storeImportLastUpdate": null,
    "botTestingNote": null,
    "botTestingStatus": null,
    "store_logo": "public/images/storesImage/apupabove.com.webp",
    "store_category": "38ec8507-4446-4878-92fd-1454f1f70fd3",
    "store_search_target": "",
    "store_tag": null,
    "store_facebook": "https://www.facebook.com/heyapupabove",
    "store_instagram": "https://instagram.com/apupabove",
    "store_twitter": "",
    "store_youtube": "",
    "store_email": "",
    "store_phone": null,
    "store_help_desk": "",
    "store_contact_page": "",
    "store_country": "",
    "store_how_to_use_coupon": "",
    "store_FAQ": null,
    "store_program_platform": null,
    "store_disclaimer": "",
    "store_template": "",
    "store_rating": null,
    "store_view_count": null,
    "store_average_rating": null,
    "store_location_code": null,
    "bestDiscount": null,
    "store_description": "\"Apupabove.com\" is an online store that primarily specializes in selling dog food. What sets this store apart is their focus on creating genuinely healthy and nutritious meals for dogs. They offer various recipes, all made with human-grade ingredients to ensure high nutritional value. The meals are cooked sous-vide, a method that retains more nutrients than traditional cooking, enhancing the food's taste and texture. The store also offers customizable meal plans to cater to different dog breeds, sizes, and dietary needs. The site is also designed to be convenient to navigate, so users can easily select products based on their dog's needs. Although their food might be more expensive than regular pet food, the company prides itself on offering improved health benefits for pets.",
    "store_name": "A Pup Above",
    "store_slug": null,
    "store_status": "PAUSED",
    "store_affiliate_link": "",
    "store_priority_score": null,
    "store_best_discount": null,
    "store_tags": "",
    "store_tiktok": "",
    "store_phone_number": "",
    "store_address": "",
    "store_last_updated": {
      "$date": "2024-08-22T10:09:37.716Z"
    },
    "store_last_checked": {
      "$date": "2024-08-22T10:09:37.716Z"
    },
    "store_saving_tips": "",
    "store_faq": "",
    "store_payment_modes": ""
  },
  {
    "_id": {
      "$oid": "66c70e627d81d1e34aee75e8"
    },
    "id": "102",
    "storeImportId": 1,
    "store_website": "asmallorange.com",
    "store_priority": "low",
    "store_affiliate_url": "https://alrigh.com/out/anwok5",
    "name": "A Small Orange",
    "slug": "a-small-orange",
    "status": "PAUSED",
    "lastUpdate": "2023-08-03T09:07:49.000Z",
    "creationDate": "2023-08-02T10:15:05.000Z",
    "storeImportLastUpdate": "2023-08-02T10:26:21.000Z",
    "botTestingNote": null,
    "botTestingStatus": null,
    "store_logo": "",
    "store_category": null,
    "store_search_target": "",
    "store_tag": null,
    "store_facebook": "",
    "store_instagram": "",
    "store_twitter": "",
    "store_youtube": "",
    "store_email": "",
    "store_phone": null,
    "store_help_desk": "",
    "store_contact_page": "",
    "store_country": "",
    "store_how_to_use_coupon": "",
    "store_FAQ": null,
    "store_program_platform": null,
    "store_disclaimer": "",
    "store_template": "",
    "store_rating": null,
    "store_view_count": null,
    "store_average_rating": null,
    "store_location_code": null,
    "bestDiscount": null,
    "store_description": "",
    "store_name": "A Small Orange",
    "store_slug": "a-small-orange",
    "store_status": "PAUSED",
    "store_affiliate_link": "",
    "store_priority_score": null,
    "store_best_discount": null,
    "store_tags": "",
    "store_tiktok": "",
    "store_phone_number": "",
    "store_address": "",
    "store_last_updated": {
      "$date": "2024-08-22T10:09:37.716Z"
    },
    "store_last_checked": {
      "$date": "2024-08-22T10:09:37.716Z"
    },
    "store_saving_tips": "",
    "store_faq": "",
    "store_payment_modes": ""
  },
  {
    "_id": {
      "$oid": "66c70e627d81d1e34aee75e9"
    },
    "id": "1039",
    "storeImportId": 1,
    "store_website": "a2hosting.com",
    "store_priority": "low",
    "store_affiliate_url": "https://alrigh.com/out/1iey9h",
    "name": "A2 Hosting",
    "slug": "a2-hosting",
    "status": "PAUSED",
    "lastUpdate": "2024-07-26T07:40:00.000Z",
    "creationDate": "2023-08-02T10:15:05.000Z",
    "storeImportLastUpdate": "2023-08-02T10:26:21.000Z",
    "botTestingNote": null,
    "botTestingStatus": null,
    "store_logo": "",
    "store_category": null,
    "store_search_target": "",
    "store_tag": null,
    "store_facebook": "",
    "store_instagram": "",
    "store_twitter": "",
    "store_youtube": "",
    "store_email": "",
    "store_phone": null,
    "store_help_desk": "",
    "store_contact_page": "",
    "store_country": "",
    "store_how_to_use_coupon": "",
    "store_FAQ": null,
    "store_program_platform": null,
    "store_disclaimer": "",
    "store_template": "",
    "store_rating": null,
    "store_view_count": null,
    "store_average_rating": null,
    "store_location_code": null,
    "bestDiscount": null,
    "store_description": "",
    "store_name": "A2 Hosting",
    "store_slug": "a2-hosting",
    "store_status": "PAUSED",
    "store_affiliate_link": "",
    "store_priority_score": null,
    "store_best_discount": null,
    "store_tags": "",
    "store_tiktok": "",
    "store_phone_number": "",
    "store_address": "",
    "store_last_updated": {
      "$date": "2024-08-22T10:09:37.716Z"
    },
    "store_last_checked": {
      "$date": "2024-08-22T10:09:37.716Z"
    },
    "store_saving_tips": "",
    "store_faq": "",
    "store_payment_modes": ""
  },
  {
    "_id": {
      "$oid": "66c70e627d81d1e34aee75ea"
    },
    "id": "320d50ee-0a1a-4cc5-a716-ed7d93687dfe",
    "storeImportId": 0,
    "store_website": "https://a7xworld.com",
    "store_priority": null,
    "store_affiliate_url": null,
    "name": "A7X World",
    "slug": null,
    "status": "PAUSED",
    "lastUpdate": null,
    "creationDate": "2024-07-26T07:02:12.000Z",
    "storeImportLastUpdate": null,
    "botTestingNote": null,
    "botTestingStatus": null,
    "store_logo": "https://www.rankcdn.com/cdn-cgi/image/quality=90,onerror=redirect,format=webp,fit=cover,width=150,height=150/couponseeker.com/A7X-World-Coupon-Codes.jpg",
    "store_category": "7f04e84c-6f33-4c72-a244-3ee3f7c24931",
    "store_search_target": "",
    "store_tag": null,
    "store_facebook": "",
    "store_instagram": "",
    "store_twitter": "",
    "store_youtube": "",
    "store_email": "",
    "store_phone": null,
    "store_help_desk": "",
    "store_contact_page": "",
    "store_country": "",
    "store_how_to_use_coupon": "",
    "store_FAQ": null,
    "store_program_platform": null,
    "store_disclaimer": "",
    "store_template": "",
    "store_rating": null,
    "store_view_count": null,
    "store_average_rating": null,
    "store_location_code": null,
    "bestDiscount": null,
    "store_description": "",
    "store_name": "A7X World",
    "store_slug": null,
    "store_status": "PAUSED",
    "store_affiliate_link": "",
    "store_priority_score": null,
    "store_best_discount": null,
    "store_tags": "",
    "store_tiktok": "",
    "store_phone_number": "",
    "store_address": "",
    "store_last_updated": {
      "$date": "2024-08-22T10:09:37.716Z"
    },
    "store_last_checked": {
      "$date": "2024-08-22T10:09:37.716Z"
    },
    "store_saving_tips": "",
    "store_faq": "",
    "store_payment_modes": ""
  },
  {
    "_id": {
      "$oid": "66c70e627d81d1e34aee75eb"
    },
    "id": "bcf82c44-4e47-45d8-bb4a-41ec1393f484",
    "storeImportId": 0,
    "store_website": "https://aaatoysandcollectibles.com",
    "store_priority": null,
    "store_affiliate_url": null,
    "name": "AAA Toys and Collectibles",
    "slug": null,
    "status": "PAUSED",
    "lastUpdate": null,
    "creationDate": "2024-07-26T07:02:12.000Z",
    "storeImportLastUpdate": null,
    "botTestingNote": null,
    "botTestingStatus": null,
    "store_logo": "https://www.rankcdn.com/cdn-cgi/image/quality=90,onerror=redirect,format=webp,fit=cover,width=150,height=150/couponseeker.com/AAA-Toys-and-Collectibles.jpg",
    "store_category": "7f04e84c-6f33-4c72-a244-3ee3f7c24931",
    "store_search_target": "",
    "store_tag": null,
    "store_facebook": "",
    "store_instagram": "",
    "store_twitter": "",
    "store_youtube": "",
    "store_email": "",
    "store_phone": null,
    "store_help_desk": "",
    "store_contact_page": "",
    "store_country": "",
    "store_how_to_use_coupon": "",
    "store_FAQ": null,
    "store_program_platform": null,
    "store_disclaimer": "",
    "store_template": "",
    "store_rating": null,
    "store_view_count": null,
    "store_average_rating": null,
    "store_location_code": null,
    "bestDiscount": null,
    "store_description": "",
    "store_name": "AAA Toys and Collectibles",
    "store_slug": null,
    "store_status": "PAUSED",
    "store_affiliate_link": "",
    "store_priority_score": null,
    "store_best_discount": null,
    "store_tags": "",
    "store_tiktok": "",
    "store_phone_number": "",
    "store_address": "",
    "store_last_updated": {
      "$date": "2024-08-22T10:09:37.716Z"
    },
    "store_last_checked": {
      "$date": "2024-08-22T10:09:37.716Z"
    },
    "store_saving_tips": "",
    "store_faq": "",
    "store_payment_modes": ""
  },
  {
    "_id": {
      "$oid": "66c70e627d81d1e34aee75ec"
    },
    "id": "72e5d5de-0f03-469f-b815-904701b0b4d9",
    "storeImportId": 0,
    "store_website": "https://gear.aarmy.com",
    "store_priority": null,
    "store_affiliate_url": null,
    "name": "AARMY Gear",
    "slug": null,
    "status": "ACTIVE",
    "lastUpdate": null,
    "creationDate": "2024-07-26T12:07:32.000Z",
    "storeImportLastUpdate": null,
    "botTestingNote": null,
    "botTestingStatus": null,
    "store_logo": "",
    "store_category": "3cdf31e3-b867-4611-bf36-e464ac92cb2a",
    "store_search_target": "",
    "store_tag": null,
    "store_facebook": "",
    "store_instagram": "https://www.instagram.com/aarmy/",
    "store_twitter": "",
    "store_youtube": "",
    "store_email": "",
    "store_phone": null,
    "store_help_desk": "",
    "store_contact_page": "",
    "store_country": "",
    "store_how_to_use_coupon": "",
    "store_FAQ": null,
    "store_program_platform": null,
    "store_disclaimer": "",
    "store_template": "",
    "store_rating": null,
    "store_view_count": null,
    "store_average_rating": null,
    "store_location_code": null,
    "bestDiscount": null,
    "store_description": "Gear.aarmy.com is an online store that specializes in fitness gear and apparel. It offers a range of products curated specifically for passionate fitness enthusiasts and those who are dedicated to their training. The product catalogue includes t-shirts, tank tops, hoodies, and accessories like caps and bags. It's associated with AARMY, a fitness and training community co-founded by top trainers Akin Akman and Angela Davis. The brand embodies a strong, military-inspired aesthetic throughout its clothing line, designed to make users feel empowered. The store provides an easy online shopping experience, allowing fitness enthusiasts to buy merchandise that suits their workout needs and lifestyle.",
    "store_name": "AARMY Gear",
    "store_slug": null,
    "store_status": "PAUSED",
    "store_affiliate_link": "",
    "store_priority_score": null,
    "store_best_discount": null,
    "store_tags": "",
    "store_tiktok": "",
    "store_phone_number": "",
    "store_address": "",
    "store_last_updated": {
      "$date": "2024-08-22T10:09:37.716Z"
    },
    "store_last_checked": {
      "$date": "2024-08-22T10:09:37.716Z"
    },
    "store_saving_tips": "",
    "store_faq": "",
    "store_payment_modes": ""
  },
  {
    "_id": {
      "$oid": "66c70e627d81d1e34aee75ed"
    },
    "id": "322bde82-f691-4a04-8d55-dede9e58ae18",
    "storeImportId": 0,
    "store_website": "https://aarons.com",
    "store_priority": null,
    "store_affiliate_url": null,
    "name": "Aaron's",
    "slug": null,
    "status": "ACTIVE",
    "lastUpdate": null,
    "creationDate": "2024-07-26T12:07:32.000Z",
    "storeImportLastUpdate": null,
    "botTestingNote": null,
    "botTestingStatus": null,
    "store_logo": "",
    "store_category": "9524baf6-07fd-4e8f-a009-a0f5ec15f761",
    "store_search_target": "",
    "store_tag": null,
    "store_facebook": "",
    "store_instagram": "",
    "store_twitter": "",
    "store_youtube": "",
    "store_email": "",
    "store_phone": null,
    "store_help_desk": "",
    "store_contact_page": "",
    "store_country": "",
    "store_how_to_use_coupon": "",
    "store_FAQ": null,
    "store_program_platform": null,
    "store_disclaimer": "",
    "store_template": "",
    "store_rating": null,
    "store_view_count": null,
    "store_average_rating": null,
    "store_location_code": null,
    "bestDiscount": null,
    "store_description": "Aarons.com is an online store that sells a wide array of products including furniture, electronics, and appliances. It's essentially a one-stop-shop for all your home need items. You can find everything from sofas, beds, and dining sets, to laptops, TVs, and refrigerators. The great thing about Aarons.com is that they offer multiple payment options, including lease-to-own, which can be helpful for people not wanting or able to pay the full price upfront. They also provide delivery and setup services for their larger items such as appliances and furniture. It's like going to a big box store from the comfort of your own home.",
    "store_name": "Aaron's",
    "store_slug": null,
    "store_status": "ACTIVE",
    "store_affiliate_link": "",
    "store_priority_score": null,
    "store_best_discount": null,
    "store_tags": "",
    "store_tiktok": "",
    "store_phone_number": "",
    "store_address": "",
    "store_last_updated": {
      "$date": "2024-08-22T10:09:37.716Z"
    },
    "store_last_checked": {
      "$date": "2024-08-22T10:09:37.716Z"
    },
    "store_saving_tips": "",
    "store_faq": "",
    "store_payment_modes": ""
  },
  {
    "_id": {
      "$oid": "66c70e627d81d1e34aee75ee"
    },
    "id": "d7e17603-b67a-4fcb-a49f-5b9759a46c11",
    "storeImportId": 0,
    "store_website": "https://aarpdriversafety.org",
    "store_priority": null,
    "store_affiliate_url": null,
    "name": "AARP Driver Safety",
    "slug": null,
    "status": "ACTIVE",
    "lastUpdate": null,
    "creationDate": "2024-07-26T12:07:32.000Z",
    "storeImportLastUpdate": null,
    "botTestingNote": null,
    "botTestingStatus": null,
    "store_logo": "",
    "store_category": "811d48f1-863a-494b-bc9d-714a7eab3d4e",
    "store_search_target": "",
    "store_tag": null,
    "store_facebook": "",
    "store_instagram": "",
    "store_twitter": "",
    "store_youtube": "",
    "store_email": "",
    "store_phone": null,
    "store_help_desk": "",
    "store_contact_page": "",
    "store_country": "",
    "store_how_to_use_coupon": "",
    "store_FAQ": null,
    "store_program_platform": null,
    "store_disclaimer": "",
    "store_template": "",
    "store_rating": null,
    "store_view_count": null,
    "store_average_rating": null,
    "store_location_code": null,
    "bestDiscount": null,
    "store_description": "AARPdriversafety.org is an educational platform designed primarily for mature drivers. This online resource, established by the American Association of Retired Persons (AARP), offers courses to help drivers enhance their driving skills, concentrate on areas such as defensive driving techniques, new traffic laws and rules, as well as how age may affect driving. It encourages drivers to stay safe on the road and potentially offers benefits like discounts on auto insurance. Besides, one doesn't need to be an AARP member to take the courses. All in all, it's an effective platform to keep individuals safer on the road during their mature years.",
    "store_name": "AARP Driver Safety",
    "store_slug": null,
    "store_status": "PAUSED",
    "store_affiliate_link": "",
    "store_priority_score": null,
    "store_best_discount": null,
    "store_tags": "",
    "store_tiktok": "",
    "store_phone_number": "",
    "store_address": "",
    "store_last_updated": {
      "$date": "2024-08-22T10:09:37.716Z"
    },
    "store_last_checked": {
      "$date": "2024-08-22T10:09:37.716Z"
    },
    "store_saving_tips": "",
    "store_faq": "",
    "store_payment_modes": ""
  }]

module.exports = AllStores